export function resolvePhotographLocale(value) {
  const normalized = (value || 'zh-CN').toLowerCase()
  if (normalized === 'zh-hant-hk') return 'zh-HK'
  if (normalized.startsWith('zh-hk')) return 'zh-HK'
  if (normalized.startsWith('zh-tw') || normalized.startsWith('zh-hant')) return 'zh-TW'
  if (normalized.startsWith('zh')) return 'zh-CN'
  if (normalized.startsWith('ja')) return 'ja'
  if (normalized.startsWith('ko')) return 'ko'
  return 'en'
}

const PHOTOGRAPH_COPY = {
  'zh-CN': {
    detailTitle: '作品详情',
    lifeTab: '最美生活照',
    campusTab: '最美校园照',
    publishAction: '我要晒照',
    empty: '暂无照片作品',
    anonymousAuthor: '匿名作者',
    anonymousUser: '匿名',
    commentPlaceholder: '说点什么...',
    sendAction: '发送',
    statsPhotos: '照片总数',
    statsComments: '评论总数',
    statsLikes: '点赞总数',
    titleLabel: '标题/名字',
    titlePlaceholder: '输入照片标题或你的名字',
    typeLabel: '照片类型',
    typeLife: '生活照',
    typeCampus: '校园照',
    mainImageLabel: '选择主图',
    subImagesLabel: '选择副图（选填，最多三张）',
    clearImagesAction: '清空图片',
    contentLabel: '说点什么吧',
    contentPlaceholder: '选填，可以填写感慨/对大学的期待...',
    submitAction: '确认提交',
    titleRequired: '标题不能为空',
    mainImageRequired: '请选择主图',
    uploadLoading: '正在上传...',
    publishSuccess: '发布成功',
    emptyComment: '评论内容不能为空',
    commentTooLong: '评论不能超过50字',
    selfAuthor: '我',
    authorAvatarAlt: '作者头像',
    commentAvatarAlt: '评论头像',
    mainPreviewAlt: '主图预览',
    subPreviewAlt: '副图预览',
    formatImageBadge: (count) => `${count}图`,
    formatLikeMetric: (count) => `${count} 点赞`,
    formatCommentMetric: (count) => `${count} 评论`,
    formatContentCount: (count) => `${count}/150字`
  },
  'zh-HK': {
    detailTitle: '作品詳情',
    lifeTab: '最美生活照',
    campusTab: '最美校園照',
    publishAction: '我要曬照',
    empty: '暫無照片作品',
    anonymousAuthor: '匿名作者',
    anonymousUser: '匿名',
    commentPlaceholder: '說點什麼...',
    sendAction: '發送',
    statsPhotos: '照片總數',
    statsComments: '評論總數',
    statsLikes: '點讚總數',
    titleLabel: '標題/名字',
    titlePlaceholder: '輸入照片標題或你的名字',
    typeLabel: '照片類型',
    typeLife: '生活照',
    typeCampus: '校園照',
    mainImageLabel: '選擇主圖',
    subImagesLabel: '選擇副圖（選填，最多三張）',
    clearImagesAction: '清空圖片',
    contentLabel: '說點什麼吧',
    contentPlaceholder: '選填，可以寫下感想或對大學的期待...',
    submitAction: '確認提交',
    titleRequired: '標題不能為空',
    mainImageRequired: '請選擇主圖',
    uploadLoading: '正在上傳...',
    publishSuccess: '發布成功',
    emptyComment: '評論內容不能為空',
    commentTooLong: '評論不能超過50字',
    selfAuthor: '我',
    authorAvatarAlt: '作者頭像',
    commentAvatarAlt: '評論頭像',
    mainPreviewAlt: '主圖預覽',
    subPreviewAlt: '副圖預覽',
    formatImageBadge: (count) => `${count}圖`,
    formatLikeMetric: (count) => `${count} 點讚`,
    formatCommentMetric: (count) => `${count} 評論`,
    formatContentCount: (count) => `${count}/150字`
  },
  'zh-TW': {
    detailTitle: '作品詳情',
    lifeTab: '最美生活照',
    campusTab: '最美校園照',
    publishAction: '我要曬照',
    empty: '暫無照片作品',
    anonymousAuthor: '匿名作者',
    anonymousUser: '匿名',
    commentPlaceholder: '說點什麼...',
    sendAction: '發送',
    statsPhotos: '照片總數',
    statsComments: '評論總數',
    statsLikes: '按讚總數',
    titleLabel: '標題/名字',
    titlePlaceholder: '輸入照片標題或你的名字',
    typeLabel: '照片類型',
    typeLife: '生活照',
    typeCampus: '校園照',
    mainImageLabel: '選擇主圖',
    subImagesLabel: '選擇副圖（選填，最多三張）',
    clearImagesAction: '清空圖片',
    contentLabel: '說點什麼吧',
    contentPlaceholder: '選填，可以寫下感想或對大學的期待...',
    submitAction: '確認提交',
    titleRequired: '標題不能為空',
    mainImageRequired: '請選擇主圖',
    uploadLoading: '正在上傳...',
    publishSuccess: '發布成功',
    emptyComment: '評論內容不能為空',
    commentTooLong: '評論不能超過50字',
    selfAuthor: '我',
    authorAvatarAlt: '作者頭像',
    commentAvatarAlt: '評論頭像',
    mainPreviewAlt: '主圖預覽',
    subPreviewAlt: '副圖預覽',
    formatImageBadge: (count) => `${count}圖`,
    formatLikeMetric: (count) => `${count} 按讚`,
    formatCommentMetric: (count) => `${count} 評論`,
    formatContentCount: (count) => `${count}/150字`
  },
  en: {
    detailTitle: 'Photo Details',
    lifeTab: 'Best Daily Photos',
    campusTab: 'Best Campus Photos',
    publishAction: 'Post Photos',
    empty: 'No photo posts yet',
    anonymousAuthor: 'Anonymous Author',
    anonymousUser: 'Anonymous',
    commentPlaceholder: 'Say something...',
    sendAction: 'Send',
    statsPhotos: 'Photos',
    statsComments: 'Comments',
    statsLikes: 'Likes',
    titleLabel: 'Title / Name',
    titlePlaceholder: 'Enter a photo title or your name',
    typeLabel: 'Photo Type',
    typeLife: 'Daily Photo',
    typeCampus: 'Campus Photo',
    mainImageLabel: 'Choose Main Photo',
    subImagesLabel: 'Choose Extra Photos (optional, up to 3)',
    clearImagesAction: 'Clear Images',
    contentLabel: 'Say Something',
    contentPlaceholder: 'Optional. Share your thoughts or expectations for college...',
    submitAction: 'Submit',
    titleRequired: 'Title is required',
    mainImageRequired: 'Please choose a main photo',
    uploadLoading: 'Uploading...',
    publishSuccess: 'Published successfully',
    emptyComment: 'Comment cannot be empty',
    commentTooLong: 'Comment must be 50 characters or fewer',
    selfAuthor: 'Me',
    authorAvatarAlt: 'Author avatar',
    commentAvatarAlt: 'Comment avatar',
    mainPreviewAlt: 'Main image preview',
    subPreviewAlt: 'Extra image preview',
    formatImageBadge: (count) => `${count} photos`,
    formatLikeMetric: (count) => `${count} Likes`,
    formatCommentMetric: (count) => `${count} Comments`,
    formatContentCount: (count) => `${count}/150`
  },
  ja: {
    detailTitle: '作品詳細',
    lifeTab: '生活写真',
    campusTab: 'キャンパス写真',
    publishAction: '写真を投稿',
    empty: 'まだ写真作品はありません',
    anonymousAuthor: '匿名作者',
    anonymousUser: '匿名',
    commentPlaceholder: 'コメントを入力...',
    sendAction: '送信',
    statsPhotos: '写真数',
    statsComments: 'コメント数',
    statsLikes: 'いいね数',
    titleLabel: 'タイトル / 名前',
    titlePlaceholder: '写真タイトルまたはあなたの名前を入力',
    typeLabel: '写真タイプ',
    typeLife: '生活写真',
    typeCampus: 'キャンパス写真',
    mainImageLabel: 'メイン画像を選択',
    subImagesLabel: '追加画像を選択（任意、最大3枚）',
    clearImagesAction: '画像をクリア',
    contentLabel: 'ひとこと',
    contentPlaceholder: '任意。感想や大学への期待を書けます...',
    submitAction: '投稿する',
    titleRequired: 'タイトルを入力してください',
    mainImageRequired: 'メイン画像を選択してください',
    uploadLoading: 'アップロード中...',
    publishSuccess: '投稿しました',
    emptyComment: 'コメント内容を入力してください',
    commentTooLong: 'コメントは50文字以内で入力してください',
    selfAuthor: '自分',
    authorAvatarAlt: '作者のアバター',
    commentAvatarAlt: 'コメントのアバター',
    mainPreviewAlt: 'メイン画像プレビュー',
    subPreviewAlt: '追加画像プレビュー',
    formatImageBadge: (count) => `${count}枚`,
    formatLikeMetric: (count) => `${count} いいね`,
    formatCommentMetric: (count) => `${count} コメント`,
    formatContentCount: (count) => `${count}/150`
  },
  ko: {
    detailTitle: '작품 상세',
    lifeTab: '일상 사진',
    campusTab: '캠퍼스 사진',
    publishAction: '사진 올리기',
    empty: '아직 사진 작품이 없습니다',
    anonymousAuthor: '익명 작성자',
    anonymousUser: '익명',
    commentPlaceholder: '한마디 남겨보세요...',
    sendAction: '전송',
    statsPhotos: '사진 수',
    statsComments: '댓글 수',
    statsLikes: '좋아요 수',
    titleLabel: '제목 / 이름',
    titlePlaceholder: '사진 제목이나 이름을 입력하세요',
    typeLabel: '사진 유형',
    typeLife: '일상 사진',
    typeCampus: '캠퍼스 사진',
    mainImageLabel: '대표 사진 선택',
    subImagesLabel: '추가 사진 선택 (선택 사항, 최대 3장)',
    clearImagesAction: '이미지 비우기',
    contentLabel: '한마디',
    contentPlaceholder: '선택 사항입니다. 소감이나 대학에 대한 기대를 남겨보세요...',
    submitAction: '등록하기',
    titleRequired: '제목을 입력하세요',
    mainImageRequired: '대표 사진을 선택하세요',
    uploadLoading: '업로드 중...',
    publishSuccess: '게시되었습니다',
    emptyComment: '댓글 내용을 입력하세요',
    commentTooLong: '댓글은 50자 이하여야 합니다',
    selfAuthor: '나',
    authorAvatarAlt: '작성자 아바타',
    commentAvatarAlt: '댓글 아바타',
    mainPreviewAlt: '대표 사진 미리보기',
    subPreviewAlt: '추가 사진 미리보기',
    formatImageBadge: (count) => `${count}장`,
    formatLikeMetric: (count) => `${count} 좋아요`,
    formatCommentMetric: (count) => `${count} 댓글`,
    formatContentCount: (count) => `${count}/150`
  }
}

export function getPhotographCopy(locale) {
  return PHOTOGRAPH_COPY[resolvePhotographLocale(locale)] || PHOTOGRAPH_COPY.en
}
