/**
 * 首页功能元数据，与功能管理、首页共用。
 * 结构：{ id, name, icon, path, defaultVisible }，外链项含 type、key。
 */
export const ALL_FEATURES = [
  { id: 'grade', name: '成绩查询', icon: 'icon-grade', path: '/grade', defaultVisible: true },
  { id: 'schedule', name: '课表查询', icon: 'icon-schedule', path: '/schedule', defaultVisible: true },
  { id: 'cet', name: '四六级查询', icon: 'icon-cet', path: '/cet', defaultVisible: true },
  { id: 'collection', name: '馆藏查询', icon: 'icon-collection', path: '/collection', defaultVisible: true },
  { id: 'book', name: '我的图书馆', icon: 'icon-book', path: '/book', defaultVisible: true },
  { id: 'evaluate', name: '教学评价', icon: 'icon-evaluate', path: '/evaluate', defaultVisible: true },
  { id: 'spare', name: '教室查询', icon: 'icon-spare', path: '/spare', defaultVisible: true },
  { id: 'kaoyan', name: '考研查询', icon: 'icon-kaoyan', path: '/kaoyan', defaultVisible: true },
  { id: 'pe', name: '体测查询', icon: 'icon-pe', path: '/pe', defaultVisible: true },
  { id: 'card', name: '消费查询', icon: 'icon-card', path: '/card', defaultVisible: true },
  { id: 'cardInfo', name: '我的饭卡', icon: 'icon-cardInfo', path: '/card/info', defaultVisible: true },
  { id: 'news', name: '新闻通知', icon: 'icon-news', path: '/news', defaultVisible: true },
  { id: 'data', name: '信息查询', icon: 'icon-data', path: '/data', defaultVisible: true },
  { id: 'ershou', name: '二手交易', icon: 'icon-ershou', path: '/ershou', defaultVisible: true },
  { id: 'lostandfound', name: '失物招领', icon: 'icon-lostandfound', path: '/lostandfound', defaultVisible: true },
  { id: 'secret', name: '校园树洞', icon: 'icon-secret', path: '/secret', defaultVisible: true },
  { id: 'photograph', name: '拍好校园', icon: 'icon-photograph', path: '/photograph', defaultVisible: true },
  { id: 'express', name: '表白墙', icon: 'icon-express', path: '/express', defaultVisible: true },
  { id: 'dating', name: '卖室友', icon: 'icon-dating', path: '/dating', defaultVisible: true },
  { id: 'topic', name: '话题', icon: 'icon-topic', path: '/topic', defaultVisible: true },
  { id: 'delivery', name: '全民快递', icon: 'icon-delivery', path: '/delivery', defaultVisible: true },
  { id: 'calendar', name: '学期校历', icon: 'icon-calendar', path: null, type: 'external', key: 'calendar', defaultVisible: true },
  { id: 'government', name: '政务服务', icon: 'icon-government', path: null, type: 'external', key: 'government', defaultVisible: true },
  { id: 'student', name: '学信网', icon: 'icon-student', path: null, type: 'external', key: 'student', defaultVisible: true },
  { id: 'volunteer', name: 'i志愿', icon: 'icon-volunteer', path: null, type: 'external', key: 'volunteer', defaultVisible: true },
  { id: 'healthcode', name: '粤康码', icon: 'icon-healthcode', path: null, type: 'external', key: 'healthcode', defaultVisible: true },
  { id: 'travelcode', name: '通信行程码', icon: 'icon-travelcode', path: null, type: 'external', key: 'travelcode', defaultVisible: true },
  { id: 'ncov', name: '疫情动态', icon: 'icon-ncov', path: null, type: 'external', key: 'ncov', defaultVisible: true },
  { id: 'about', name: '关于应用', icon: 'icon-about', path: '/about', defaultVisible: true },
]

/** 首页图标路径映射（id -> 图片路径），与 public/img/function 对应 */
export const FEATURE_ICON_SRC = {
  grade: '/img/function/grade.png',
  schedule: '/img/function/schedule.png',
  cet: '/img/function/cet.png',
  collection: '/img/function/collection.png',
  book: '/img/function/library.png',
  evaluate: '/img/function/evaluate.png',
  spare: '/img/function/spare.png',
  kaoyan: '/img/function/kaoyan.png',
  pe: '/img/function/sport.png',
  card: '/img/function/card.png',
  cardInfo: '/img/function/cardInfo.png',
  news: '/img/function/news.png',
  data: '/img/function/data.png',
  ershou: '/img/function/ershou.png',
  lostandfound: '/img/function/lostandfound.png',
  secret: '/img/function/secret.png',
  photograph: '/img/function/photograph.png',
  express: '/img/function/express.png',
  dating: '/img/function/dating.png',
  topic: '/img/function/topic.png',
  delivery: '/img/function/delivery.png',
  calendar: '/img/function/calendar.png',
  government: '/img/function/goverment.png',
  student: '/img/function/student.png',
  volunteer: '/img/function/volunteer.png',
  healthcode: '/img/function/healthcode.png',
  travelcode: '/img/function/travelcode.png',
  ncov: '/img/function/ncov.png',
  about: '/img/function/about.png',
}
