export function resolveDatingLocale(value) {
  const normalized = (value || 'zh-CN').toLowerCase()
  if (normalized === 'zh-hant-hk') return 'zh-HK'
  if (normalized.startsWith('zh-hk')) return 'zh-HK'
  if (normalized.startsWith('zh-tw') || normalized.startsWith('zh-hant')) return 'zh-TW'
  if (normalized.startsWith('zh')) return 'zh-CN'
  if (normalized.startsWith('ja')) return 'ja'
  if (normalized.startsWith('ko')) return 'ko'
  return 'en'
}

const DATING_HOME_COPY = {
  'zh-CN': {
    myAction: '我的',
    femaleTab: '小姐姐',
    maleTab: '小哥哥',
    studentSuffix: '学生',
    fromPrefix: '来自',
    unknown: '未知',
    empty: '暂无内容',
  },
  'zh-HK': {
    myAction: '我的',
    femaleTab: '小姐姐',
    maleTab: '小哥哥',
    studentSuffix: '學生',
    fromPrefix: '來自',
    unknown: '未知',
    empty: '暫無內容',
  },
  'zh-TW': {
    myAction: '我的',
    femaleTab: '小姐姐',
    maleTab: '小哥哥',
    studentSuffix: '學生',
    fromPrefix: '來自',
    unknown: '未知',
    empty: '暫無內容',
  },
  en: {
    myAction: 'My',
    femaleTab: 'Girls',
    maleTab: 'Boys',
    studentSuffix: 'student',
    fromPrefix: 'From',
    unknown: 'Unknown',
    empty: 'No profiles yet',
  },
  ja: {
    myAction: 'マイ',
    femaleTab: '女性',
    maleTab: '男性',
    studentSuffix: '学生',
    fromPrefix: '出身',
    unknown: '不明',
    empty: 'まだ投稿がありません',
  },
  ko: {
    myAction: '내 정보',
    femaleTab: '여학생',
    maleTab: '남학생',
    studentSuffix: '학생',
    fromPrefix: '출신',
    unknown: '알 수 없음',
    empty: '아직 게시물이 없습니다',
  },
}

const DATING_CENTER_COPY = {
  'zh-CN': {
    title: '互动中心',
    anonymous: '匿名',
    recentUpdate: '最近更新',
    published: '已发布',
    acceptAction: '同意',
    rejectAction: '拒绝',
    acceptedShown: '已同意，已展示联系方式',
    rejected: '已拒绝',
    emptyReceived: '暂无收到的请求',
    emptySent: '暂无发出的请求',
    emptyPosts: '暂无发布',
    contactLabel: '联系方式：',
    qqLabel: 'QQ',
    wechatLabel: '微信',
    hideAction: '隐藏',
    acceptSuccess: '已同意，联系方式已展示',
    rejectSuccess: '已拒绝',
    hideSuccess: '已隐藏',
    statusPending: '待处理',
    statusAccepted: '已同意',
    statusRejected: '已拒绝',
    statusUnknown: '未知',
    hideTitle: '确认隐藏',
    hideDescription: '确定要隐藏这条发布吗？隐藏后他人将无法在卖室友大厅看到此内容。',
  },
  'zh-HK': {
    title: '互動中心',
    anonymous: '匿名',
    recentUpdate: '最近更新',
    published: '已發布',
    acceptAction: '同意',
    rejectAction: '拒絕',
    acceptedShown: '已同意，已展示聯絡方式',
    rejected: '已拒絕',
    emptyReceived: '暫無收到的請求',
    emptySent: '暫無發出的請求',
    emptyPosts: '暫無發布',
    contactLabel: '聯絡方式：',
    qqLabel: 'QQ',
    wechatLabel: '微信',
    hideAction: '隱藏',
    acceptSuccess: '已同意，聯絡方式已展示',
    rejectSuccess: '已拒絕',
    hideSuccess: '已隱藏',
    statusPending: '待處理',
    statusAccepted: '已同意',
    statusRejected: '已拒絕',
    statusUnknown: '未知',
    hideTitle: '確認隱藏',
    hideDescription: '確定要隱藏這條發布嗎？隱藏後其他人將無法在賣室友大廳看到此內容。',
  },
  'zh-TW': {
    title: '互動中心',
    anonymous: '匿名',
    recentUpdate: '最近更新',
    published: '已發布',
    acceptAction: '同意',
    rejectAction: '拒絕',
    acceptedShown: '已同意，已展示聯絡方式',
    rejected: '已拒絕',
    emptyReceived: '暫無收到的請求',
    emptySent: '暫無發出的請求',
    emptyPosts: '暫無發布',
    contactLabel: '聯絡方式：',
    qqLabel: 'QQ',
    wechatLabel: '微信',
    hideAction: '隱藏',
    acceptSuccess: '已同意，聯絡方式已展示',
    rejectSuccess: '已拒絕',
    hideSuccess: '已隱藏',
    statusPending: '待處理',
    statusAccepted: '已同意',
    statusRejected: '已拒絕',
    statusUnknown: '未知',
    hideTitle: '確認隱藏',
    hideDescription: '確定要隱藏這則發布嗎？隱藏後其他人將無法在賣室友大廳看到此內容。',
  },
  en: {
    title: 'Interaction Center',
    anonymous: 'Anonymous',
    recentUpdate: 'Recently updated',
    published: 'Published',
    acceptAction: 'Accept',
    rejectAction: 'Reject',
    acceptedShown: 'Accepted. Contact information is now visible.',
    rejected: 'Rejected',
    emptyReceived: 'No requests received yet',
    emptySent: 'No requests sent yet',
    emptyPosts: 'No posts yet',
    contactLabel: 'Contact:',
    qqLabel: 'QQ',
    wechatLabel: 'WeChat',
    hideAction: 'Hide',
    acceptSuccess: 'Accepted. Contact information is now visible.',
    rejectSuccess: 'Rejected',
    hideSuccess: 'Hidden',
    statusPending: 'Pending',
    statusAccepted: 'Accepted',
    statusRejected: 'Rejected',
    statusUnknown: 'Unknown',
    hideTitle: 'Confirm Hide',
    hideDescription: 'Hide this post? Once hidden, other users will no longer see it in Roommate Match.',
  },
  ja: {
    title: '交流センター',
    anonymous: '匿名',
    recentUpdate: '最近更新',
    published: '公開済み',
    acceptAction: '承認',
    rejectAction: '拒否',
    acceptedShown: '承認済みで、連絡先が表示されています。',
    rejected: '拒否しました',
    emptyReceived: '受信したリクエストはありません',
    emptySent: '送信したリクエストはありません',
    emptyPosts: '投稿はありません',
    contactLabel: '連絡先：',
    qqLabel: 'QQ',
    wechatLabel: 'WeChat',
    hideAction: '非表示',
    acceptSuccess: '承認済みで、連絡先が表示されています。',
    rejectSuccess: '拒否しました',
    hideSuccess: '非表示にしました',
    statusPending: '保留中',
    statusAccepted: '承認済み',
    statusRejected: '拒否済み',
    statusUnknown: '不明',
    hideTitle: '非表示の確認',
    hideDescription: 'この投稿を非表示にしますか？ 非表示にすると、ルームメイト一覧に表示されなくなります。',
  },
  ko: {
    title: '상호작용 센터',
    anonymous: '익명',
    recentUpdate: '최근 업데이트',
    published: '게시됨',
    acceptAction: '수락',
    rejectAction: '거절',
    acceptedShown: '수락되어 연락처가 표시되었습니다.',
    rejected: '거절됨',
    emptyReceived: '받은 요청이 없습니다',
    emptySent: '보낸 요청이 없습니다',
    emptyPosts: '게시물이 없습니다',
    contactLabel: '연락처:',
    qqLabel: 'QQ',
    wechatLabel: 'WeChat',
    hideAction: '숨기기',
    acceptSuccess: '수락되어 연락처가 표시되었습니다.',
    rejectSuccess: '거절됨',
    hideSuccess: '숨김 처리됨',
    statusPending: '대기 중',
    statusAccepted: '수락됨',
    statusRejected: '거절됨',
    statusUnknown: '알 수 없음',
    hideTitle: '숨기기 확인',
    hideDescription: '이 게시물을 숨길까요? 숨기면 다른 사용자가 룸메이트 매치에서 이 내용을 볼 수 없습니다.',
  },
}

export function getDatingHomeCopy(locale) {
  return DATING_HOME_COPY[resolveDatingLocale(locale)] || DATING_HOME_COPY.en
}

export function getDatingCenterCopy(locale) {
  return DATING_CENTER_COPY[resolveDatingLocale(locale)] || DATING_CENTER_COPY.en
}

export function getDatingGradeText(t, grade, unknownLabel) {
  const label = unknownLabel || t('common.unknown')
  const map = {
    1: t('grade.year.freshman'),
    2: t('grade.year.sophomore'),
    3: t('grade.year.junior'),
    4: t('grade.year.senior'),
  }
  return map[grade] || label
}
