package edu.gdei.gdeiassistant.Enum.Charge;

public enum GetServerKeyCodeResultEnum {
    GETKEYCODE_SUCCESS, UNSUPPORT_CLIENTTYPE, UNSUPPORT_SECURITYVERSION, NULL_USERINFORMATION, INCORRECT_USERINFORMATION
}
