-- H2 schema for mapper integration tests (MySQL compatibility mode)

CREATE TABLE IF NOT EXISTS ershou (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(24) NOT NULL,
  name VARCHAR(25) NOT NULL,
  description VARCHAR(100) NOT NULL,
  price FLOAT DEFAULT 0,
  location VARCHAR(30) NOT NULL,
  type TINYINT DEFAULT 0,
  qq VARCHAR(20),
  phone VARCHAR(11),
  state TINYINT DEFAULT 1,
  publish_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lostandfound (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(24) NOT NULL,
  name VARCHAR(25) NOT NULL,
  description VARCHAR(100) NOT NULL,
  location VARCHAR(30) NOT NULL,
  item_type TINYINT DEFAULT 0,
  lost_type TINYINT DEFAULT 0,
  qq VARCHAR(20),
  wechat VARCHAR(20),
  phone VARCHAR(11),
  state TINYINT DEFAULT 0,
  publish_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS express (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(24) NOT NULL,
  nickname VARCHAR(10) NOT NULL,
  realname VARCHAR(10),
  self_gender TINYINT NOT NULL,
  name VARCHAR(10) NOT NULL,
  content VARCHAR(250) NOT NULL,
  person_gender TINYINT NOT NULL,
  publish_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS express_like (
  id INT AUTO_INCREMENT PRIMARY KEY,
  express_id INT NOT NULL,
  username VARCHAR(24) NOT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS express_comment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  express_id INT NOT NULL,
  username VARCHAR(24) NOT NULL,
  comment VARCHAR(200) NOT NULL,
  publish_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS express_guess (
  id INT AUTO_INCREMENT PRIMARY KEY,
  express_id INT NOT NULL,
  username VARCHAR(24) NOT NULL,
  result TINYINT DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS delivery_order (
  order_id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(24) NOT NULL,
  order_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(10) NOT NULL,
  number VARCHAR(11) NOT NULL,
  phone VARCHAR(11) NOT NULL,
  price DECIMAL(7,2) NOT NULL,
  company VARCHAR(10) NOT NULL,
  address VARCHAR(50) NOT NULL,
  state TINYINT DEFAULT 0,
  remarks VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS delivery_trade (
  trade_id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  username VARCHAR(24) NOT NULL,
  state TINYINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS secret_content (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(24) NOT NULL,
  content VARCHAR(100) NOT NULL,
  theme TINYINT DEFAULT 1,
  type TINYINT DEFAULT 0,
  timer TINYINT DEFAULT 0,
  state TINYINT DEFAULT 0,
  publish_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS secret_comment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content_id INT NOT NULL,
  username VARCHAR(24) NOT NULL,
  comment VARCHAR(200) NOT NULL,
  avatar_theme INT DEFAULT 0,
  publish_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS secret_like (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content_id INT NOT NULL,
  username VARCHAR(24) NOT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS topic (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(24) NOT NULL,
  topic VARCHAR(15) NOT NULL,
  content VARCHAR(250) NOT NULL,
  count INT DEFAULT 0,
  publish_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS topic_like (
  id INT AUTO_INCREMENT PRIMARY KEY,
  topic_id INT NOT NULL,
  username VARCHAR(24) NOT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS charge_order (
  order_id VARCHAR(36) PRIMARY KEY,
  username VARCHAR(24) NOT NULL,
  amount INT NOT NULL,
  status VARCHAR(32) NOT NULL,
  idempotency_key_hash VARCHAR(64),
  payload_fingerprint VARCHAR(64),
  request_id VARCHAR(64),
  device_id_hash VARCHAR(64),
  external_order_no VARCHAR(128),
  external_trade_no VARCHAR(128),
  school_trade_no VARCHAR(128),
  payment_url_hash VARCHAR(64),
  error_code VARCHAR(64),
  error_message_sanitized VARCHAR(255),
  unknown_reason VARCHAR(255),
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  submitted_at DATETIME,
  completed_at DATETIME,
  last_checked_at DATETIME,
  check_count INT DEFAULT 0 NOT NULL,
  manual_review_at DATETIME,
  manual_review_note VARCHAR(255),
  version INT DEFAULT 0 NOT NULL
);
